- src/index.js
First one should close #8. Second one just makes sense to me: we create params as an array, then spread it to memoize only to have memoize coerce it back to an array. Compile with babel and check out how much extraneous code it generates.
> Minor perf improvements

- package.json
Updated package.json this should remove warnings when using reselect.
> added more information to package.json

- src/index.js
It's necessary to have at least two parameters in the returning function definition in order to play nice with `react-redux`'s `connect` function.
> Reverts last commit.

- README.md
Work in progress experiments to address issues #7 , #20 , #27. The API section of the README has some examples.
There is one breaking change. createSelectorCreator now takes a memoize function instead of a valueEquals function.
> WIP 1.0.0 (Configurable memoize / variadic dependencies / pass props to selector)

- src/index.js
- test/test_selector.js
I ran into an issue while working on some selectors where an input selector was undefined.  However, the error is thrown only when the selector is used and does not provide a terribly useful stack trace.  Checking the input selectors on selector creation:
* Fails sooner, when the selector is originally created
* Provides us a stack trace directly to the problematic code
A very basic `typeof` check to ensure than input selectors are functions.
* Ensure input selectors are functions during selector creation
* Throw if invalid, allowing for a useful stack trace
> Validate input selectors on selector creation

- README.md
I clicked the "See here" link and discovered a couple broken references around this anchor change. Here's a quick fix. :)
> Fix README references to createSelector

- package.json
Support IE8
Changing to `exports.__esModule = true` manually in the imported code makes it work. Without it, `Object.defineProperty` is used.
```js
Object.defineProperty(exports, '__esModule', {
value: true
});
```
This is a no-op in core-js for IE8, so the `import`-transform in babel doesn't work.
And yes, I know IE8 isn't supported by MS anymore, but this is a small change.
Workaround for now is to use `const { createSelector } = require('reselect');`, but I don't want that :laughing:
> Use loose mode for modules

- src/index.js
- test/test_selector.js
Noticed an issue with `defaultMemoize` when you pass in an ordered subset of the memoized arguments, it will incorrectly returned the memoized value.
See test for an example (it fails without the argument length check).
> Fix issue with defaultMemoize and multiple arguments

- README.md
- package.json
- src/reselect.d.ts
This PR allows typescript users to simply `npm install reselect` to get typings support. For more information on how this works, check out this link: https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages
As a note, I gave @frankwallis the commit authorship, because he wrote the original commits for the typings. He was not involved in this PR, however. Sorry for any confusion!
> Reference typings in package.json

- README.md
Previously, it was unclear for people skimming the docs that the advice found in the `Sharing Selectors Across Multiple Components` section only applies for those trying to solve the specific problem mentioned in the previous section. As a result, I'm sure some people were padding private copies of selectors to different components even in situations where they didn't need to. This makes the documentation more clear.
> Clarify when it's necessary to copy selectors

- .gitignore
- package.json
Adds a command in `package.json` to build a browser-ready UMD file to a `dist`
folder.  All files are compiled to a `reselect.js` file and attached to a global
variable name of Reselect.
Closes #99
> Add UMD build command

- .babelrc
- .gitignore
- package.json
Adds a build step for the `jsnext:main` which compiles all features _except_ for modules to an `es` folder.  The previous `compile` command is now the `commonjs` build which ends up in the `lib` directory.
Fixes #103
> Add jsnext build

- package.json
There is no es folder in npm package. eslint-plugin-import throw errors in my projects
> Add `es` folder to package.json

- README.md
The state passed to `shopItemsSelector` did not have a `shop` property.
> Fix exampleState in readme

- .travis.yml
This adds Node v6 to the list of versions Travis will test against.
> Add Node 6 to Travis

- .gitignore
- package.json
Fixes issue #134, adds three small dev-only dependencies. I've diffed compiled files on Windows 10 and OS X 10.10.5.
Whitespace changes on authors in package.json were done by npm automatically (Node 6.2.1).
> Change npm scripts to work cross-platform.

- src/index.js
- test/test_selector.js
The issue is when `func` throws exception the last `args` already saved and next calling of memoized func will return `null` instead of recalculating `func` again. If we save `args` after calling of `func` we save `args` only for "good" result and don't for exceptions.
> Cancel args memorization if func throws exception

- src/reselect.d.ts
- typescript_test/common.ts
- typescript_test/should_compile/index.ts
- typescript_test/should_not_compile/index.ts
- typescript_test/test.js
Sadly, I can't find a way to support either format without duplicating the same approach taken for the multiple-argument signature. The definition file is now 10X bigger than the library itself. :(
Fix some eslint complaints.
Use trailing commas consistently.
It's possible there's a way to do this with ...args: Selector<>[], but I can't figure out how to preserve the selector / combiner return/argument pairing with that approach. Changes to Typescript 2.1 (supporting object spread) might open up some possibilities here.
> Support array argument for createSelector.

- README.md
I think it is probably sensible to have an empty string as the `initialValue` of this example reducer, otherwise the first argument in the array is not stringified.
I know it's just an example, but as I'd copied and pasted this as a starting point for something a little more complicated I ran into some problems (which I traced back to this) and I'm guessing other people might do the same.
Cheers
> Updated lodash memoized example function with initialValue

- src/index.js
Closes https://github.com/reactjs/reselect/issues/170
_For posterity_
Previously, not updating `lastArgs` when the equality test passed
meant that if an object goes from shallow equal -> deep equal ->
shallow equal accross updates, that transition back to shallow equal
would continue to require deep equality checks. This could lead
to large slowdowns for complex objects. See the github issue
for details.
> Make defaultMemoizer store the latest args if the equality test passes

- src/index.js
`defaultMemoize` creates an unnecessary inline function on (nearly) every invocation of the returned function. This affects both speed and memory usage. The function has been moved to the outer scope.
A very simple benchmark shows ~ 30% perf improvement in Chrome and ~ 150% in Firefox: https://www.measurethat.net/Benchmarks/Show/259/9/reselect-defaultmemoize
> Improve defaultMemoize performance

- package.json
- src/index.js
- test/test_selector.js
ES6, object/array spreading and the like make the code much more readable and easier 
to reason about.
However, this trade-off comes at the cost of performance. When running a selector, a copy of the
parameters were cloned many times which added a trivial amount of overhead for a single call. 
However if a selector was called thousands of times (e.x. a large list of items) then the trivial
amount of overhead added upwards of around 1 second to all selector calls regardless of cache
hits/misses.
Normally, readable code > super optimized code but selectors can be called very often and the
overhead associated with those calls has to be minimal.
The first commit in this PR adds a test that calls a basic selector a million times. Before the
performance increase it takes ~2.5 seconds on my …
> Speedup cache hit performance of selectors

- src/index.d.ts
- typescript_test/test.ts
Add resultFunc, recomputations and resetRecomputations to the Typescript definition file.
This is just an adaptation of https://github.com/reactjs/reselect/pull/167 from @lukevenn against the new branch 3.0.0
> Improve Typescript definitions

- test/test_selector.js
On master, the inputSelectors are called with an extra `undefined` param when the selector is only called with the state. This is usually not a problem, but in my specific case, some inputSelectors are curried functions, and in the result func, I use the returned function. I know it kind of defies the concept of `createSelector`, but in these cases, perf does not matter, and it lets me use the same API/patterns consistently in my app.
This bug is due to the `props` param (possibly undefined) passed to `dependency`, on this [line](https://github.com/reactjs/reselect/blob/master/src/index.js#L54).
I was planning to submit a fix, however, the 3.0.0 rewrite did fix this bug! So here is a test to prevent any regressions on this side :) If you add this test to master, you'll see that it breaks. …
> Test to ensure inputSelectors called with same params as the selector

- README.md
The FAQ states that Reselect doesn't take additional arguments, but this doesn't cover the common scenario of those additional arguments being available as Redux props. (I needed a selector that took some additional arguments (which were available as Redux props), went straight to the FAQ (overlooking the "example" section), and saw an answer that I thought meant that I was out of luck. #162 seems to be from a user who followed a similar thought process.) This change hopefully clarifies things and adds an additional place to access this information.
> Add note about Redux props to FAQ

- README.md
"React props," not "Redux props." This fixes the terminology for my change in #242.
> Fix terminology

- README.md
I didn't understand why a selector created with `createSelector` doesn't simply return a cache on the same set of arguments until I read [Q: Can I share a selector across multiple components](https://github.com/reactjs/reselect#q-can-i-share-a-selector-across-multiple-components). I think mentioning cache size would help to understand it better.
> mention cache size in the problem

- src/index.d.ts
- typescript_test/test.ts
Fixes https://github.com/reactjs/reselect/issues/237.
This is backwards-compatible.
> Update Selector types for correct extension

- README.md
we don't want `ReferenceError` in our unit tests 🤓
> Explicit use of myComposedSelector in readme unit test

- package.json
First off, thanks for this library! It is the missing link between redux stores and view components and is absolutely fantastic!
Secondly, I realize unminifed, the library is like 4.6k, so this isn't a huge issue. I do think, though, as a best practice, all umd libs should provide both a minified and an unminified version of the code. As such, I've added uglify to compress the dist lib down to a minified version coming in at just over 2k.
> Add minified umd package.

- package.json
`jsnext:main` is deprecated in favor of `module` key.
We can keep both to ensure the greatest compatibility with all bundlers.
> chore: added `module` key to let modern bundlers pick ES version

- README.md
Reflect that the chrome extension is out and be more specific about what it can do!
> Updated reselect tools verbiage

- README.md
The original verb, "change," does not agree with the subject, "one" (as opposed to, "arguments").
* Reference: Guideline number 5 on [Purdue University > ... > Grammar > Subject/Verb Agreement](https://owl.english.purdue.edu/owl/resource/599/01/)
> Fix grammatical error

- src/index.d.ts
- typescript_test/test.ts
- typescript_test/tsconfig.json
Here is the related issue https://github.com/reactjs/reselect/issues/264
Right now we have to do typings like this:
```
const selectorOne = (state: State) => state.something;
const selectorTwo = (state: State) => state.other;
createSelector([selectorOne, selectorTwo], () => ...);
```
This PR allows us to do typings like this:
```
const selectorOne = (state: { something: string }) => state.something;
const selectorTwo = (state: { other: number }) => state.other;
createSelector([selectorOne, selectorTwo], () => ...);
```
Let me know if I should change anything, thanks!
> Allow Differently Typed Selectors

- src/index.d.ts
- typescript_test/test.ts
Currently array version of `createSelector` typing has fixed number of selectors known at compile-time. However `createSelector`'s implementation supports any number of selectors determined at run-time. Technically input selectors can have different return types. That's impossible to describe in TypeScript. But it's possible to describe the case when all selectors have same return type. For example when input selectors are generated for each element of a container that has nr of elements  fixed during selector's lifetime:
```ts
createSelector(containerWithFixedNrOfElements.map(obj => () => obj.value), (...values) => expensiveCalculation(values))
```
> added typings for dynamic array of uniform selectors

- src/index.js
- test/test_selector.js
This PR allows us to test which dependencies are passed into a selector.
Original conversation: https://github.com/reactjs/reselect/issues/76#issuecomment-299194186
**It matters which dependencies a selector uses**.  For example, if we have two selectors that use the same `resultFunc`...
```es6
const lookUp = (hash, ids) => ids.map((id) => hash[id]);
const getMyValues = createSelector(
getMyHash,
getMyIds,
lookUp,
);
const getYourValues = createSelector(
getYourHash,
getYourIds,
lookUp,
);
```
...testing the `resultFunc` isn't enough.  We actually need to test that the first two functions are what we expect them to be.  We can do this with an integration test (passing in the entire state into the whole selector) but, it forces us to essentially re-test `getMyHash`, `getMyIds`.
We've been …
> Expose selector dependencies for testing purposes

- src/index.js
In addition to memoizedResultFunc.
> Use provided memoize function for selectors

- README.md
The `createSelector()` version of the `createStructuredSelector()` example uses a third, undeclared input-selector. This pull request removes `mySelectorC` and `c` which don't appear in the second snippet.
> Fix createStructuredSelector() example snippet

- src/index.js
This improves tree-shakeability of the `createSelectorCreator`
> Add PURE annotation to a top-level createSelectorCreator call

- README.md
In order to use lodash's isEqual function, you must import lodash.isequal (I added), not lodash.isEqual (was previously in the readme.).
> Updated README lodash imports

- README.md
- README_RU.md
This PR corrects the order of the arguments for `defaultEqualityCheck` in the documentation.
The `equalityCheck` function is called as such in the code:
```js
const length = prev.length
for (let i = 0; i < length; i++) {
if (!equalityCheck(prev[i], next[i])) {
return false
}
}
```
while `defaultEqualityCheck` in the README is specified as:
```js
function defaultEqualityCheck(currentVal, previousVal) {
return currentVal === previousVal
}
```
> Correct defaultEqualityCheck example arguments

- src/defaultMemoize.ts
- test/test_selector.ts
I tried out `resultEqualityCheck` and it caused my selector to keep recalculating because the cache doesn't get updated.
> Update defaultMemoize cache even if resultEqualityCheck is a hit

- src/index.ts
- src/types.ts
This would make the `OutputSelector` backward compatible with the pre-4.1.0 version.
See comment https://github.com/reduxjs/reselect/issues/533#issuecomment-957963101
> Make OutputSelector backwards compatible w/ < 4.1.0 version

- src/types.ts
- typescript_test/test.ts
This PR:
- Updates the input selector parameter inference to correctly handle cases where a parameter is `undefined` or `null` as opposed to unions that contain `undefined` at all.
This should now work much better for functions that have optional parameters, as well as functions with mismatched input selector parameter lengths.
> Fix intersection of parameters that are undefined

- .github/workflows/build-and-test-types.yml
- src/index.ts
- typescript_test/test.ts
- typescript_test/tsconfig.json
This PR:
- Exports the `CreateSelectorFunction` type, because apparently exports using `createStructuredSelector` were broken without it.
- Adds TS 4.5 to the test matrix
Supersedes #553 .
> Export CreateSelectorFunction to fix createStructuredSelector usage

- src/types.ts
- typescript_test/test.ts
I've taken my Pr - https://github.com/reduxjs/reselect/pull/564 and simplified the change to only remove the condition that breaks. 
It is incorrect because when a problem happens with params, `[never]` extends `[EmptyObject]` and `RemainingItems` becomes `[never]`. 
But when we get to OutputSelector
```
export type OutputSelector<
S extends SelectorArray,
Result,
Combiner extends UnknownFunction,
Params extends readonly any[] = never // MergeParameters<S>
> = Selector<GetStateFromSelectors<S>, Result, Params> &
OutputSelectorFields<Combiner>
```
never is the default to mean that there should not be any params (e.g. no problem at all, rather than [never] which means there is a type problem - there is 1 parameter of value never, which then will error with no params and error with 1 param). …
> Fix #563 - Make it an error when the typings become incorrect

- src/types.ts
- src/versionedTypes/index.ts
- src/versionedTypes/ts47-mergeParameters.ts
- typescript_test/test.ts
The state parameter of the result of createSelector was of type never if input selectors were a mix of explicit and spread selectors. Additionally, the type of extra parameters are lost if the input has this format.
This PR aims to allow the combining of explicitly defined input selectors and using rest syntax in the end. It does so by making sure that the type of the array that is part of the rest syntax is transformed into a normal type before merging the parameter tuples. This is valid since we really don't care whether we have 1 or 10 selectors in the array that is spread as long as the types are the same.
This is related to [issue 601](https://github.com/reduxjs/reselect/issues/601) where some more details can be found in the conversation.
> Infer correct state when input selectors are a mix of explicit and rest syntax in createSelector

- package.json
- tsup.config.ts
This PR:
- Updates the build config to add a browser-compatible ESM production artifact that has `process.env.NODE_ENV` compiled away, and a real Webpack 4-compatible artifact with `?.` and `??` transpiled.
> Build browser ESM and Webpack 4 compat artifacts, and add sourcemaps

- README.md
README didn't get updated when stability check changed from `boolean | 'once'` to `'always' | 'once' | 'never'`
This fixes it :)
> Fix README to match inputStabilityCheck options

- package.json
- src/index.ts
- test/autotrackMemoize.spec.ts
- test/perfComparisons.spec.ts
- test/reselect.spec.ts
- test/tsconfig.json
- typescript_test/argsMemoize.typetest.ts
- yarn.lock
This PR:
- Renames the WIP `autotrackMemoize` function to `unstable_autotrackMemoize` for clarity
- Bumps Vitest to the latest version because A) why not, and B) I was seeing some weirdness running the test suite locally after merging the last couple PRs
> Rename to `unstable_autotrackMemoize` and bump Vitest version

- README.md
After a brief conversation with @markerikson on Discord on creating selectors with multiple arguments, I suggested to expand the docs with his clarification and here it is.
> docs: expand FAQ on multiple arguments

- src/createSelectorCreator.ts
- test/reselect.spec.ts
> Match `resetRecomputations` and `resetDependencyRecomputations` behavior to their types

- src/defaultMemoize.ts
- src/types.ts
- src/weakMapMemoize.ts
Makes `EqualityFn` a tiny bit more type-safe so that `a` and `b` in `(a, b) => boolean` have to be of the same type.
> Make `EqualityFn` slightly more type-safe.

- package.json
- src/devModeChecks/identityFunctionCheck.ts
- src/devModeChecks/inputStabilityCheck.ts
- test/identityFunctionCheck.test.ts
- test/inputStabilityCheck.spec.ts
> Add stack to dev check warnings

- src/createSelectorCreator.ts
- src/devModeChecks/identityFunctionCheck.ts
- test/identityFunctionCheck.test.ts
- test/lruMemoize.test.ts
- test/reselect.spec.ts
- test/weakmapMemoize.spec.ts
This PR attempts to reduce the number of false positives identified by `identityFunctionCheck` by making two changes:
1. Only produce a warning if the result function is only passed one argument.
2. Compare the first argument passed to the result function with the value returned by the result function. There are some edge cases where this could prevent some false positives, although admittedly, they're likely rare (one hypothetical edge case is added as a test).
> Reduce `identityFunctionCheck` false positives

- website/docs/FAQ.mdx
- website/docs/api/development-only-stability-checks.mdx
- website/docs/introduction/how-does-reselect-work.mdx
- website/docs/related-projects.mdx
> Fix cut content inside TOC of docs

- website/docusaurus.config.ts
- website/src/components/HomepageFeatures/index.tsx
> Remove redundant Svg requires from components in docs

- src/weakMapMemoize.ts
> Fix `_lastResult.deref` is not a function (it is undefined) in React Native and Expo applications

- package.json
- yarn.lock
> Bump RTK and React-Redux to latest versions

- typescript_test/typesTestUtils.ts
> Fix `expectExactType` to be compatible with TypeScript 5.4

- src/lruMemoize.ts
- test/lruMemoize.test.ts
> Ensure `lruMemoize` correctly memoizes when `maxSize` is set to a number less than 1

- website/src/components/HomepageFeatures/index.tsx
- [The `JSX` namespace in TypeScript](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#the-jsx-namespace-in-typescript)
- [`scoped-jsx` codemod](https://github.com/eps1lon/types-react-codemod/?tab=readme-ov-file#scoped-jsx)
> Replace usage of deprecated `JSX` global namespace with `React.JSX`

- src/utils.ts
- test/lruMemoize.test.ts
I'm not sure what's the reasoning for using a string constant for the not-found value, but an object feels both safer (real uniqueness, the string `'NOT_FOUND'` could make the logic fail) and more performant (no `strcmp()` if both values are strings) which is handy when the selectors are called very often.
I've used a private class instance for the empty value because you seem to use the value type `NOT_FOUND_TYPE`, otherwise I would have gone with a `Symbol('not-found')` or an empty object, but any of these would be fine I think.
> Fix: use unique value for NOT_FOUND
